### ISSUE TITLE
Allow base 64 output

### ISSUE THREAD

**Issue by sitch** [mwmiller/excon#1]
Currently when you call indent, a `File.write`, and subsequent `File.read` is required.  What if you just want to get the base64 string?  Perhaps the option `type: nil` would work?

**Comment by mwmiller** [comment]
Unless I am misunderstanding, the package currently works much as you would like.  From the documentation:

```
`filename`: a string for the file name (default: nil, image data is returned)
```

Thus, if the `filename` option is `nil` (as it is by default) the image data is returned directly.

Do you require a different interface for your use case?

**Comment by mwmiller** [comment]
Seeing no further discussion on what might be needed, I am closing this issue.
